import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue, Oswald, Quicksand, Atkinson_Hyperlegible} from "next/font/google";
import "./globals.css";
import NavBar from "./component/fixed-elements/navbar";
import Footer from "./component/fixed-elements/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({ subsets: ["latin"], weight: "400", variable: "--font-bebas-neue"  });

const oswald = Oswald({ subsets:["latin"], weight:["400", "700"], variable: "--font-oswald" });

const quicksand = Quicksand({ subsets:["latin"], weight:["300", "400", "700"], variable: "--font-quicksand"});

const atkinsonHyperlegible = Atkinson_Hyperlegible({subsets:["latin"], weight:["400", "700"], variable:"--font-atkinson-hyperlegible" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} ${oswald.variable} ${quicksand.variable} ${atkinsonHyperlegible.className} antialiased`}
      >
        <NavBar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
